### PR TITLE
Make aws credentials optional.

### PR DESCRIPTION
**Pull request by jmcarp**
Allows use of aws instance profiles, which is recommended instead of
using iam users where possible.

### CODE REVIEW

**Comment by jeffpak** [comment]
@jmcarp 

Only making the access and secrets keys optional got us wondering how you were feeding the iam role to the efsbroker.  We're assuming you're using the default IAM profile that bosh supports. https://bosh.io/docs/aws-iam-instance-profiles.html?  Specifically this comment:

> In addition to configuring AWS CPI in the deployment manifest to use IAM instance profile as a credentials source, also set default IAM instance profile for all future deployed VMs:

properties:
  aws: &aws
    credentials_source: env_or_profile
    default_iam_instance_profile: deployed-vm
    # ...

makes us think that it is possible to instruct BOSH to create VMs with the provided role which is then handled internally by the aws sdk.

Is that a correct read of the situation?

**Comment by jmcarp** [comment]
We attach credentials to vms using instance profiles, but not using the default instance profile--that would mean we'd be granting efs permissions to all vms managed by the bosh director. We use bosh `vm_extensions` to attach instances profiles with access to efs to the vm running the broker.

In cloud config:

```yaml
vm_extensions:
- name: efs_broker
  cloud_properties:
    iam_instance_profile: efs_broker
```

In deploy manifest:

```yaml
instance_groups:
- name: efs_broker
  vm_extensions: [efs_broker]
  ...
```

**Comment by jmcarp** [comment]
@jeffpak @julian-hj: I updated the docs to mark the access key and secret as optional and describe how to use instance profiles instead.

**Comment by jeffpak** [comment]
We've merged your pull request. Thanks for providing the necessary documentation to use this method.

**Pull request merged**
